name: "Custom Fullscreen Kiosk"
description: "A custom Kiosk browser built to bypass security and allow USB camera access."
version: "1.0.0"
slug: "custom-kiosk"
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
startup: application
boot: auto
host_network: true
video: true
options: {}
schema: {}
